server:
  port: 8089
  
  
spring:
  application:
    name: SHIPPING-SERVICE
    
    
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka 
  instance:
    hostname: localhost 
    
  